SYS-1028: Display PO Line Details
UCLALibrary/voyager-archive pull request #18
Opened 2022-10-18 23:07 UTC by ztucker4

Relates to [SYS-1028](https://jira.library.ucla.edu/browse/SYS-1028)

This draft PR satisfies the basic acceptance criteria of the ticket (duplicated below). However, I'd like some feedback/ideas on how best to present the PO Line Items to users. In this draft, I have put them into a single column-style table. I have some intuition that a line item should probably be displayed as a row, but there are a lot of columns and horizontal scrolling seems much worse than vertical scrolling. 

- A link is added to the line# data in the po_display.html template
- The link passes PoLineItemView.line_item_id via URL to a view
- The view retrieves full data for that line_item_id and displays it in a separate template
- There can be multiple rows in the QuerySet for each line_item_id, in cases where a line's funding is split over multiple funds
- Rows are ordered by PoLineItemView.split_fund_seq
- Data is displayed in basic table(s) like item_display

2022-10-19 00:54 UTC, akohler reviewed
@ztucker4 Overall, this is a great start.  Here's are my suggestions & comments for this draft PR:
* Definitely not one super-long row! Horizontal would not work at all.
* Maybe split this into multiple tables (2-3 columns, in 1 row), similar to the PO Header or the Item displays.  Possibly group by general, financial, and other?  Like Item, there may be different numbers of values in each column.
* One long column might still work, maybe with some fields could be grouped for a slightly shorter display.  For example, see what I did in the PO Header with [created](https://github.com/UCLALibrary/voyager-archive/blob/main/voyager_archive/templates/voyager_archive/po_display.html#L42-L43).  However, I'm not sure that's best, since the point of this display is to show all the discrete fields, and only a few pairs of these have potential for grouping... most would still be single values.  I prefer multiple columns, if reasonable categories can be found for each.
* I think the hyperlinked line number display should change, to make it more obvious to users there's something to click.  I suggest changing `#N` to either `Line #N` or `#N (details)`, where `details` might be the hyperlink.

2022-10-20 19:38 UTC, ztucker4 commented
@akohler, I've made some changes and this is now ready for review. I broke the PO Line Item info up into several tables that fit on one (largeish) screen, as shown in the screenshot below. Let me know if anything should be re-arranged here. I also made the linking more visible using your "(details)" suggestion.

Currently, the PO detail page does not display the search form on top like the other pages so far. Let me know if that is needed for this PR (I'll probably need some help if so :) )
![image](https://user-images.githubusercontent.com/7283991/197041365-f7441ef5-2929-49c3-8a97-32e161b40c9a.png)

2022-10-20 22:03 UTC, akohler commented
@ztucker4 Thanks, I'll review tomorrow morning when I'm back.  For now, I confirm that the search form does *not* need to display on these "click for details" pages.  That might change later, or we might just have a constant set of links to all 3 archives, but either way, that won't be part of this PR.  Thanks --Andy

2022-10-21 18:09 UTC, akohler requested changes
@ztucker4 I think the multi-table layout looks great, and your groupings make sense to me.

A few data elements don't display because of typos in the template, since Django is permissive and doesn't throw errors when an element does not already exist.  And there are a couple of other minor tweaks.

Please let me know when ready for re-review.  Thanks --Andy

2022-10-21 18:09 UTC, akohler commented on voyager_archive/templates/voyager_archive/po_line_display.html
> +                <td>{{ line.create_operator_ID }}</td>
@ztucker4 This should be `create_operator_id` - there's data, not currently displaying at http://127.0.0.1:8000/po_line_display/1060976 because of the difference.

2022-10-21 18:09 UTC, akohler commented on voyager_archive/templates/voyager_archive/po_line_display.html
> +                <td>{{ line.receive_operator_ID }}</td>
@ztucker4 This should be `receive_operator_id` - there's data, not currently displaying at http://127.0.0.1:8000/po_line_display/1060976 because of the difference.

2022-10-21 18:09 UTC, akohler commented on voyager_archive/templates/voyager_archive/po_line_display.html
> +                <td>{{ line.vndor_ref_num}}</td>
@ztucker4 This should be `vendor_ref_num` - there's no actual data, so I expect `None` should display at http://127.0.0.1:8000/po_line_display/1060976 like other empty values do.

2022-10-21 18:09 UTC, akohler commented on voyager_archive/templates/voyager_archive/po_line_display.html
> +                <td>{{ line.raw_amount }}</td>
@ztucker4 Add a `floatformat` to this, same as other currency amounts.

2022-10-21 18:09 UTC, akohler commented on voyager_archive/views.py
> +    ordered_po_lines = po_lines.order_by("split_fund_seq")
@ztucker4 Move this ordering into the data access point, `views_utils.get_po_lines_by_line_id()`.  I think we'll always want these lines order by `split_fund_seq`, so doing that when data is retrieved is better.

2022-10-21 18:09 UTC, akohler commented on voyager_archive/views_utils.py
> +    po_lines = PoLineItemView.objects.filter(line_item_id=line_item_id)
@ztucker4 See previous comment, adding `.order_by("split_fund_seq")` here instead of doing it in the view itself.  See `get_inv_lines()` as an example.

2022-10-21 20:03 UTC, ztucker4 commented
Hi @akohler, this is now ready for re-review. Sorry for all the typos and thanks again!

2022-10-21 20:49 UTC, akohler approved these changes
@ztucker4 Thanks for making the changes.  Looks great to me now - merging.

2022-10-21 20:50 UTC, merged